---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: go-http-counter
  name: go-http-counter
spec:
  selector:
    matchLabels:
      app: go-http-counter
  template:
    metadata:
      labels:
        app: go-http-counter
    spec:
      containers:
      - image: ghcr.io/n-arno/go-http-counter:latest
        name: go-http-counter
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: go-http-counter
  name: go-http-counter
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: go-http-counter
  type: ClusterIP
